#!/usr/bin/env node
// Creates .dev.vars for local development with fresh random secrets (never the example placeholders).
//   npm run setup:local            create .dev.vars; refuses to overwrite an existing one
//   npm run setup:local -- --force replace it
import { existsSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';

const target = '.dev.vars';
if (existsSync(target) && !process.argv.includes('--force')) {
	console.error(`${target} already exists; leaving it alone. Use --force to replace it.`);
	process.exit(1);
}

const jwt = randomBytes(48).toString('base64');
const password = randomBytes(24).toString('base64');

// .dev.vars.example lists only the secret a person chooses; local development also needs the root secret that
// `npm run deploy` generates for a real installation
writeFileSync(
	target,
	[
		'# Local development only. Generated by `npm run setup:local`; never deploy these values.',
		`JWT_SECRET=${jwt}`,
		`ADMIN_BOOTSTRAP_PASSWORD=${password}`,
		'',
	].join('\n'),
	{ mode: 0o600 },
);
console.log(`Wrote ${target} with new random secrets.`);
console.log('Open /upload/ and sign in with ADMIN_BOOTSTRAP_PASSWORD; the site creates the owner from it on first use.');
